### ISSUE TITLE
[BUG] On moving homes

### ISSUE THREAD

**Issue by IceWaffles** [Niestrat99/AT-Rewritten#111]
### Description
Error on moving homes

### Reproducing
Steps to reproduce the behaviour:
1. Do /sethome after you already have a home

### Expected Behaviour
No error

### Stacktraces

https://pastebin.com/6HYdd5Mj

[02:53:31 INFO]: etheros_ issued server command: /sethome home
[02:53:31 WARN]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: HomeMoveEvent may only be triggered synchronously.
[02:53:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[02:53:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[02:53:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
[02:53:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[02:53:31 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[02:53:31 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[02:53:31 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[02:53:31 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[02:53:31 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[02:53:31 WARN]: Caused by: java.lang.IllegalStateException: HomeMoveEvent may only be triggered synchronously.
[02:53:31 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)
[02:53:31 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[02:53:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[02:53:31 WARN]:        at AdvancedTeleport-Bukkit-6.0.0-rc.2-all.jar//io.github.niestrat99.advancedteleport.api.events.CancellableATEvent.callEvent(CancellableATEvent.java:39)
[02:53:31 WARN]:        at AdvancedTeleport-Bukkit-6.0.0-rc.2-all.jar//io.github.niestrat99.advancedteleport.api.AdvancedTeleportAPI.validateEvent(AdvancedTeleportAPI.java:93)
[02:53:31 WARN]:        at AdvancedTeleport-Bukkit-6.0.0-rc.2-all.jar//io.github.niestrat99.advancedteleport.api.Home.move(Home.java:102)
[02:53:31 WARN]:        at AdvancedTeleport-Bukkit-6.0.0-rc.2-all.jar//io.github.niestrat99.advancedteleport.api.ATPlayer.lambda$moveHome$19(ATPlayer.java:514)
[02:53:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[02:53:31 WARN]:        ... 6 more

### Server
Use /version to fill out the following information.
 - Server Type: [Purpur]
 - Server Version: [1.20.1
 - Build (where applicable): [2017]

### Plugin Information
Use /version AdvancedTeleport to fill out this information.
- Plugin version: [6.0 rc2]

### Additional Information
When you do the command, it says the home has been set but the data has not been stored succesfully

**Comment by Thatsmusic99** [comment]
Was able to resolve it in this run: https://github.com/Niestrat99/AT-Rewritten/actions/runs/5536260637

The most up-to-date dev build for v6 with other fixes is just here: https://github.com/Niestrat99/AT-Rewritten/actions/runs/5597165577

**Comment by Thatsmusic99** [comment]
Fix is now in v6.0.0-rc.3
