### ISSUE TITLE
[BUG] with spawns on folia

### ISSUE THREAD

**Issue by roggy666** [Niestrat99/AT-Rewritten#121]
When trying to install spawn, it gives an error, but if you write /setspawn, and then immediately /setmainspawn, there will be no error, but after a reboot, all spawns are erased

[00:55:16 INFO]: GZsupport issued server command: /setmainspawn
[00:55:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'setmainspawn' in plugin AdvancedTeleport v6.0.0-rc.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1048) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[folia-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2378) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2338) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:233) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:142) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.github.niestrat99.advancedteleport.api.AdvancedTeleportAPI.lambda$setSpawn$6(AdvancedTeleportAPI.java:183) ~[AdvancedTeleport-Bukkit-6.0.0-rc.3.jar:?]
        at io.github.niestrat99.advancedteleport.api.AdvancedTeleportAPI.validateEvent(AdvancedTeleportAPI.java:102) ~[AdvancedTeleport-Bukkit-6.0.0-rc.3.jar:?]
        at io.github.niestrat99.advancedteleport.api.AdvancedTeleportAPI.setSpawn(AdvancedTeleportAPI.java:167) ~[AdvancedTeleport-Bukkit-6.0.0-rc.3.jar:?]
        at io.github.niestrat99.advancedteleport.commands.spawn.SetMainSpawn.onCommand(SetMainSpawn.java:57) ~[AdvancedTeleport-Bukkit-6.0.0-rc.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 14 more

Error after /setspawn and no error with /setmainspawn

[00:58:28 INFO]: GZsupport issued server command: /setspawn
[00:58:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'setspawn' in plugin AdvancedTeleport v6.0.0-rc.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1048) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[folia-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2378) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2338) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:233) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:142) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.github.niestrat99.advancedteleport.api.AdvancedTeleportAPI.lambda$setSpawn$6(AdvancedTeleportAPI.java:183) ~[AdvancedTeleport-Bukkit-6.0.0-rc.3.jar:?]
        at io.github.niestrat99.advancedteleport.api.AdvancedTeleportAPI.validateEvent(AdvancedTeleportAPI.java:102) ~[AdvancedTeleport-Bukkit-6.0.0-rc.3.jar:?]
        at io.github.niestrat99.advancedteleport.api.AdvancedTeleportAPI.setSpawn(AdvancedTeleportAPI.java:167) ~[AdvancedTeleport-Bukkit-6.0.0-rc.3.jar:?]
        at io.github.niestrat99.advancedteleport.commands.spawn.SetSpawn.onCommand(SetSpawn.java:45) ~[AdvancedTeleport-Bukkit-6.0.0-rc.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 14 more
[00:58:32 INFO]: GZsupport issued server command: /setmainspawn

**Comment by Thatsmusic99** [comment]
The error should be fixed in https://github.com/Niestrat99/AT-Rewritten/actions/runs/6102987356?pr=105, not sure about spawns vanishing though, can you confirm that?

**Comment by roggy666** [comment]
Thank you!
