### ISSUE TITLE
[BUG] back command & Folia

### ISSUE THREAD

**Issue by roggy666** [Niestrat99/AT-Rewritten#122]
When I write /back. I got this error
[21:40:38 INFO]: GZsupport issued server command: /back
[21:40:38 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Scheduling chunk load off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239) ~[?:?]
        at net.minecraft.world.level.Level.getChunk(Level.java:524) ~[?:?]
        at net.minecraft.world.level.Level.getBlockState(Level.java:823) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:242) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.github.niestrat99.advancedteleport.commands.teleport.Back.onCommand(Back.java:78) ~[AdvancedTeleport-Bukkit-6.0.0-rc.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1048) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[folia-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2378) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2338) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:40:38 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'advancedteleport:back' in plugin AdvancedTeleport v6.0.0-rc.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1048) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[folia-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2378) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2338) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Scheduling chunk load off-main
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239) ~[?:?]
        at net.minecraft.world.level.Level.getChunk(Level.java:524) ~[?:?]
        at net.minecraft.world.level.Level.getBlockState(Level.java:823) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:242) ~[folia-1.20.1.jar:git-Folia-"f6e91e9"]
        at io.github.niestrat99.advancedteleport.commands.teleport.Back.onCommand(Back.java:78) ~[AdvancedTeleport-Bukkit-6.0.0-rc.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 14 more

**Comment by Thatsmusic99** [comment]
Should be fixed with this build: https://github.com/Niestrat99/AT-Rewritten/actions/runs/6126256560?pr=105

As an extra note, Folia has issues with events that AT depends on, which resulted in /back not working regardless for AT, even without the error. Now, it only works for death locations and AT commands like /tpa, /tpr, etc. - and changing respawn location will not work.
