### ISSUE TITLE
[BUG] Could not pass event PlayerRespawnEvent to AdvancedTeleport

### ISSUE THREAD

**Issue by honnisha** [Niestrat99/AT-Rewritten#49]
### Reproducing
Steps to reproduce the behaviour:
After player death.

### Stacktraces
```[13:42:04] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to AdvancedTeleport v5.5.2
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.getWorld(CraftServer.java:1261) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.Bukkit.getWorld(Bukkit.java:629) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.github.niestrat99.advancedteleport.config.Spawn.getProperMainSpawn(Spawn.java:172) ~[?:?]
        at io.github.niestrat99.advancedteleport.config.Spawn.getSpawn(Spawn.java:123) ~[?:?]
        at io.github.niestrat99.advancedteleport.config.Spawn.getSpawn(Spawn.java:119) ~[?:?]
        at io.github.niestrat99.advancedteleport.managers.TeleportTrackingManager.onRespawn(TeleportTrackingManager.java:123) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor269.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:933) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:828) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:823) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2593) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PacketPlayInClientCommand.a(SourceFile:30) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Server
Use /version to fill out the following information.
This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugin Information
Use /version AdvancedTeleport to fill out this information.
- AdvancedTeleport version 5.5.2

**Comment by Thatsmusic99** [comment]
Should've been fixed with 5.5.3 which released a while ago. Please ensure you are running the latest version of AT before opening an issue. If the issue consists, please re-open the issue.
