### ISSUE TITLE
[BUG] NoSuchMethodException

### ISSUE THREAD

**Issue by cjunekim** [Niestrat99/AT-Rewritten#54]
### Description
When starting the server, the advanced teleporter incurs an exception.

### Reproducing
Steps to reproduce the behaviour:
1. put the 5.5.5 version jar file in the plugin folder and run the server

### Expected Behaviour
No such exception

### Stacktraces
[19:35:00 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_15_R1.World.getDataManager()
[19:35:00 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
[19:35:00 WARN]:        at io.github.niestrat99.advancedteleport.utilities.nbt.NBTReader.getWorldNBTStorage(NBTReader.java:146)
[19:35:00 WARN]:        at io.github.niestrat99.advancedteleport.utilities.nbt.NBTReader.init(NBTReader.java:45)
[19:35:00 WARN]:        at io.github.niestrat99.advancedteleport.CoreClass$1.run(CoreClass.java:120)
[19:35:00 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:35:00 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:35:00 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:35:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[19:35:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[19:35:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

### Server
Use /version to fill out the following information.
 - Server Type: Paper
 - Server Version: 1.15.2
 - Build (where applicable): 

### Plugin Information
Use /version AdvancedTeleport to fill out this information.
- Plugin version: 5.5.5

**Comment by Thatsmusic99** [comment]
Investigating - the only side effect of this error is that offline teleportation will not work.
