### ISSUE TITLE
[BUG] NPE

### ISSUE THREAD

**Issue by weihao** [Niestrat99/AT-Rewritten#58]
### Description
NPE

### Reproducing
N/A

### Stacktraces
](https://github.com/GeyserMC/Floodgate/issues/237)

### Server
This server is running Paper version git-Paper-68 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1c779c2)
You are running the latest version
Previous version: git-Paper-60 (MC: 1.18)

### Plugin Information
5.5.6

### Additional Information
Not sure if it is Floodgate's API throwing errors or the plugin's wrong implementation causing errors. posting the issue here too.

**Comment by Thatsmusic99** [comment]
Already aware of, but appreciate opening the report so it's tracked.

**Comment by weihao** [comment]
@Thatsmusic99 ping, any updates on this?

**Comment by Thatsmusic99** [comment]
Nada, I'm afraid my access to testing tools woth floodgate/Bedrock is incredibly limited and there's been no update to the related PR either.

**Comment by Thatsmusic99** [comment]
Have got ahold of a server I can test everything with at least so if I get the chance I'll investigate it today (same goes for Errored-Innovations/HeadsPlus#84)

**Comment by Thatsmusic99** [comment]
No result reproducing, account linked and unlinked. Please confirm your floodgate and Geyser versions below using `/version floodgate` and `/version Geyser-Spigot`:

> [09:08:07 INFO]: floodgate version 2.1.0-SNAPSHOT
[09:08:07 INFO]: Allows Bedrock players to join Java edition servers while keeping the server in online mode
[09:08:07 INFO]: Website: https://github.com/GeyserMC/Floodgate/spigot
[09:08:07 INFO]: Author: GeyserMC

> [09:08:10 INFO]: Geyser-Spigot version 2.0.0-SNAPSHOT
[09:08:10 INFO]: Website: https://github.com/GeyserMC/Geyser/blob/master/pom.xml
[09:08:10 INFO]: Author: GeyserMC

If the version numbers match - as Jens mentioned in the original floodgate issue, I've no idea why the error is being thrown, so I'd like you to try a debugging [version](https://cdn.discordapp.com/attachments/269172690957369355/922056389684236308/AdvancedTeleport-Bukkit-5.5.7DEV_null.jar). Prior to the error, something along the following should be printed in the console:

> [09:22:08 INFO]: [AdvancedTeleport] Is the player online?: true
[09:22:08 INFO]: [AdvancedTeleport] Player is being tracked by floodgate?: true
[09:22:08 INFO]: [AdvancedTeleport] Floodgate player checked, UUID being checked: 00000000-0000-0000-0009-01fca418eb28, name: .ErrorTM99

This will help me realise what's going on and what I or GeyserMC can do.

**Comment by weihao** [comment]
```
[08:35:57] [Server thread/INFO]: [AdvancedTeleport] Is the player online?: true
[08:35:57] [Server thread/INFO]: [AdvancedTeleport] Floodgate player checked, UUID being checked: 00000000-0000-0000-0009-01f0c67e24e5, name: .xiaonai6318
[08:35:57] [Server thread/INFO]: [AdvancedTeleport] Player is being tracked by floodgate?: false
[08:35:57] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to AdvancedTeleport v5.5.7+DEV_${env.BUILD_NUMBER}
java.lang.NullPointerException: Cannot invoke "org.geysermc.floodgate.api.player.FloodgatePlayer.getCorrectUniqueId()" because the return value of "org.geysermc.floodgate.api.FloodgateApi.getPlayer(java.util.UUID)" is null
	at io.github.niestrat99.advancedteleport.api.ATPlayer.<init>(ATPlayer.java:61) ~[AdvancedTeleport-Bukkit-5.5.7DEV_null.jar:?]
	at io.github.niestrat99.advancedteleport.api.ATPlayer.<init>(ATPlayer.java:46) ~[AdvancedTeleport-Bukkit-5.5.7DEV_null.jar:?]
	at io.github.niestrat99.advancedteleport.api.ATPlayer.getPlayer(ATPlayer.java:312) ~[AdvancedTeleport-Bukkit-5.5.7DEV_null.jar:?]
	at io.github.niestrat99.advancedteleport.managers.TeleportTrackingManager.onDeath(TeleportTrackingManager.java:86) ~[AdvancedTeleport-Bukkit-5.5.7DEV_null.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor65.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:896) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:862) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1451) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:923) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1027) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.causeFallDamage(LivingEntity.java:1887) ~[?:?]
	at net.minecraft.world.entity.player.Player.causeFallDamage(Player.java:1709) ~[?:?]
	at net.minecraft.world.level.block.Block.fallOn(Block.java:458) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1512) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:367) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doCheckFallDamage(ServerPlayer.java:1456) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1512) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:16) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-84]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by weihao** [comment]
1.18.1

Paper
```
This server is running Paper version git-Paper-81 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c189d0)
You are running the latest version
Previous version: git-Paper-79 (MC: 1.18.1)
```
Geyser-Velocity
https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/957/

Floodgate-Velocity
https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/53/

**Comment by Thatsmusic99** [comment]
Oh goodness. That explains it, you're using Floodgate Velocity, not Spigot. No wonder. Let me see what I can do about that, I'll need to talk with the developers regarding that.

**Comment by Thatsmusic99** [comment]
Can I ask if you have floodgate on the back-end (Paper) servers?

**Comment by weihao** [comment]
Yes. That might cause problems when getting the instance

**Comment by Thatsmusic99** [comment]
I see, that should be okay but it's quite surprising. When I get the chance, I'll see what I can get.

**Comment by weihao** [comment]
if i remove the paper plugin, this error will occur since it does not read velocity
```
Could not load 'plugins/BlueMapFloodgate-1.3.6-BETA.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [floodgate]. Please download and install these plugins to run 'BlueMapFloodgate'.
```
