### ISSUE TITLE
[BUG] When used with ChunkyBorderBukkit, an error occurs.

### ISSUE THREAD

**Issue by itcools** [Niestrat99/AT-Rewritten#71]
[10:37:59] [Craft Scheduler Thread - 13 - AdvancedTeleport/WARN]: [AdvancedTeleport] Plugin AdvancedTeleport v5.5.7 generated an exception while executing task 50
java.lang.ClassCastException: class org.popcraft.chunkyborder.ChunkyBorderBukkit cannot be cast to class org.popcraft.chunkyborder.ChunkyBorder (org.popcraft.chunkyborder.ChunkyBorderBukkit and org.popcraft.chunkyborder.ChunkyBorder are in unnamed module of loader 'ChunkyBorder-1.0.64.jar' @6a242cb1)
	at io.github.niestrat99.advancedteleport.hooks.borders.ChunkyBorderHook.canUse(ChunkyBorderHook.java:16) ~[AdvancedTeleport-Bukkit-5.5.7.jar:?]
	at io.github.niestrat99.advancedteleport.managers.PluginHookManager.getRandomCoords(PluginHookManager.java:70) ~[AdvancedTeleport-Bukkit-5.5.7.jar:?]
	at io.github.niestrat99.advancedteleport.utilities.RandomCoords.generateCoords(RandomCoords.java:18) ~[AdvancedTeleport-Bukkit-5.5.7.jar:?]
	at io.github.niestrat99.advancedteleport.managers.RTPManager.addLocation(RTPManager.java:67) ~[AdvancedTeleport-Bukkit-5.5.7.jar:?]
	at io.github.niestrat99.advancedteleport.managers.RTPManager.loadWorldData(RTPManager.java:145) ~[AdvancedTeleport-Bukkit-5.5.7.jar:?]
	at io.github.niestrat99.advancedteleport.managers.RTPManager.init(RTPManager.java:29) ~[AdvancedTeleport-Bukkit-5.5.7.jar:?]
	at io.github.niestrat99.advancedteleport.CoreClass$1.run(CoreClass.java:121) ~[AdvancedTeleport-Bukkit-5.5.7.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-187]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-187]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-187]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Thatsmusic99** [comment]
This was fixed in one of our dev builds: https://ci.pluginwiki.us/job/Advanced%20Teleport/79/

**Comment by Thatsmusic99** [comment]
No worries, will close this now as the fix was published on SpigotMC.
